version: '3.8'

services:
  erp-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development Version (optional)
  erp-frontend-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev
    profiles:
      - dev

  # Optional: Backend service
  # erp-backend:
  #   image: node:18-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "3001:3001"
  #   command: npm start
  #   environment:
  #     - NODE_ENV=production